"""add_ai_settings_to_users

Revision ID: e7af8830c91a
Revises: 381198992e4f
Create Date: 2026-05-05 06:37:05.314136

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e7af8830c91a'
down_revision: Union[str, None] = '381198992e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ai_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ai_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_model')
    op.drop_column('users', 'ai_api_key')
    op.drop_column('users', 'ai_provider')
    # ### end Alembic commands ###
