"""add_seen_jobs_and_last_auto_scan

Revision ID: f210be9d917b
Revises: d367545c3854
Create Date: 2026-05-05 07:50:52.361758

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f210be9d917b'
down_revision: Union[str, None] = 'd367545c3854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seen_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_url', name='uq_user_job_url')
    )
    op.add_column('users', sa.Column('last_auto_scan_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_auto_scan_at')
    op.drop_table('seen_jobs')
    # ### end Alembic commands ###
